# Generated by Django 4.0.4 on 2022-05-05 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ArtifactKind',
            fields=[
                ('Name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Star', models.IntegerField()),
                ('Vision', models.IntegerField()),
                ('FullHp', models.IntegerField()),
                ('FullAtk', models.IntegerField()),
                ('FullDef', models.IntegerField()),
                ('SecondaryStat', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='SecondaryStat',
            fields=[
                ('Name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('MinVal', models.FloatField()),
                ('MaxVal', models.FloatField()),
                ('BaseVal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='Vision',
            fields=[
                ('Name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='Weapon',
            fields=[
                ('Name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
                ('Star', models.IntegerField()),
                ('Type', models.IntegerField()),
                ('FullAtk', models.IntegerField()),
                ('SecondaryStat', models.IntegerField()),
                ('FullSecondayStatVal', models.FloatField()),
            ],
        ),
        migrations.CreateModel(
            name='WeaponType',
            fields=[
                ('Name', models.CharField(max_length=255, primary_key=True, serialize=False, unique=True)),
            ],
        ),
    ]
